from tkinter import *
from PIL import Image,ImageTk

b=Tk()
b.title("Employee Mangement System")
b.geometry("1600x800")
b.configure(bg="#7E84F7")
frame=Frame(b,width=1600,height=600,background="#7E84F7")
frame.pack()
frame.place(relx=0,rely=0)
# img=ImageTk.PhotoImage(Image.open("D:\\python\\gui\\employ.gif"))
# l0=Label(frame,image=img)
# l0.pack()
l1=Label(frame,text="Employee Management System",font=("calibiri",30,"italic","bold"),bg="#7E84F7",fg="white")
l1.place(relx=0.2,rely=0.1)
def admin(b):
    b.destroy()
    b=Tk()
    b.title("Admin Log")
    b.geometry("1600x800")
    b.configure(bg="#7E84F7")
    frame=Frame(b,width=1600,height=600,background="#7E84F7")
    frame.pack()
    frame.place(relx=0,rely=0)
    #img=ImageTk.PhotoImage(Image.open("D:\\python\\gui\\employ.gif"))
    #l0=Label(frame,image=img)
    #l0.pack()
    l1=Label(frame,text="Admin Details",font=("calibiri",30,"italic","bold"),bg="#7E84F7",fg="white")
    l1.place(relx=0.25,rely=0.1)
    def new(b):
        b.destroy()
        b=Tk()
        b.title("New Employee")
        b.geometry("1600x800")
        b.configure(bg="#7E84F7")
        frame=Frame(b,width=1600,height=600,background="#7E84F7")
        frame.pack()
        frame.place(relx=0,rely=0)
        # img=ImageTk.PhotoImage(Image.open("D:\\python\\gui\\employ.gif"))
        # l0=Label(frame,image=img)
        # l0.pack()
        d=Label(frame,text="Employee ID",font=("arial",10,"bold"),bg="#7E84F7")
        d.place(relx=0.05,rely=0.15)
        l1=Label(frame,text="Add Employee Details",font=("calibiri",30,"italic","bold"),bg="#7E84F7",fg="white")
        l1.place(relx=0.25,rely=0.05)
        l2=Label(frame,text="Name",font=("arial",10,"bold"),bg="#7E84F7")
        l2.place(relx=0.05,rely=0.2)
        l3=Label(frame,text="Age",font=("arial",10,"bold"),bg="#7E84F7")
        l3.place(relx=0.05,rely=0.25)
        l4=Label(frame,text="Place",font=("arial",10,"bold"),bg="#7E84F7")
        l4.place(relx=0.05,rely=0.3)
        l5=Label(frame,text="DOB",font=("arial",10,"bold"),bg="#7E84F7")
        l5.place(relx=0.05,rely=0.35)
        l6=Label(frame,text="Aadhaar No",font=("arial",10,"bold"),bg="#7E84F7")
        l6.place(relx=0.05,rely=0.4)
        l7=Label(frame,text="PAN No",font=("arial",10,"bold"),bg="#7E84F7")
        l7.place(relx=0.05,rely=0.45)
        l8=Label(frame,text="HSC Reg no",font=("arial",10,"bold"),bg="#7E84F7")
        l8.place(relx=0.05,rely=0.5)
        l9=Label(frame,text="Degree Reg No",font=("arial",10,"bold"),bg="#7E84F7")
        l9.place(relx=0.05,rely=0.55)
        l10=Label(frame,text="HSC Percentage",font=("arial",10,"bold"),bg="#7E84F7")
        l10.place(relx=0.05,rely=0.6)
        l11=Label(frame,text="Degree Percentage",font=("arial",10,"bold"),bg="#7E84F7")
        l11.place(relx=0.05,rely=0.65)
        e0=Entry(b)
        e0.place(relx=0.2,rely=0.15)
        e1=Entry(b)
        e1.place(relx=0.2,rely=0.2)
        e2=Entry(b)
        e2.place(relx=0.2,rely=0.25)
        e3=Entry(b)
        e3.place(relx=0.2,rely=0.3)
        e4=Entry(b)
        e4.place(relx=0.2,rely=0.35)
        e5=Entry(b)
        e5.place(relx=0.2,rely=0.4)
        e6=Entry(b)
        e6.place(relx=0.2,rely=0.45)
        e7=Entry(b)
        e7.place(relx=0.2,rely=0.5)
        e8=Entry(b)
        e8.place(relx=0.2,rely=0.55)
        e9=Entry(b)
        e9.place(relx=0.2,rely=0.6)
        e10=Entry(b)
        e10.place(relx=0.2,rely=0.65)
        '''e0.delete(0,END)
        e1.delete(0,END)
        e2.delete(0,END)
        e3.delete(0,END)
        e4.delete(0,END)
        e5.delete(0,END)
        e6.delete(0,END)
        e7.delete(0,END)
        e8.delete(0,END)
        e9.delete(0,END)
        e10.delete(0,END)'''
        
        def add():
            file=open("New Employee.txt","a")
            file.write("\n"+e0.get()+"\t"+e1.get()+"\t"+e2.get()+"\t"+e3.get()+"\t"+e4.get()+"\t"+e5.get()+"\t"+e6.get()+"\t"+e7.get()+"\t"+e8.get()+"\t"+e9.get()+"\t"+e10.get()+"\n")
        Button(frame,text="ADD",bg="#7E84F7",font=("arial",15,"bold"),command=lambda:add()).place(relx=0.25,rely=0.8)
        b.mainloop()

    b1=Button(frame,text="New Employee",font=("Times New Roman",15,"bold"),bg="#7E84F7",command=lambda:new(b))
    b1.place(relx=0.2,rely=0.4)
        
    


    def exist(b):
        b.destroy()
        b=Tk()
        b.title("Current Employee")
        b.geometry("1600x800")
        b.configure(bg="#7E84F7")
        frame=Frame(b,width=1600,height=600,background="#7E84F7")
        frame.pack()
        frame.place(relx=0,rely=0)
        # img=ImageTk.PhotoImage(Image.open("D:\\python\\gui\\employ.gif"))
        # l0=Label(frame,image=img)
        # l0.pack()
        d=Label(frame,text="Employee ID",font=("arial",10,"bold"),bg="#7E84F7")
        d.place(relx=0.05,rely=0.15)
        l1=Label(frame,text="Add Employee Details",font=("calibiri",30,"italic","bold"),bg="#7E84F7",fg="white")
        l1.place(relx=0.25,rely=0.05)
        l2=Label(frame,text="Name",font=("arial",10,"bold"),bg="#7E84F7")
        l2.place(relx=0.05,rely=0.2)
        l3=Label(frame,text="Age",font=("arial",10,"bold"),bg="#7E84F7")
        l3.place(relx=0.05,rely=0.25)
        l4=Label(frame,text="Place",font=("arial",10,"bold"),bg="#7E84F7")
        l4.place(relx=0.05,rely=0.3)
        l5=Label(frame,text="DOB",font=("arial",10,"bold"),bg="#7E84F7")
        l5.place(relx=0.05,rely=0.35)
        l6=Label(frame,text="Aadhaar No",font=("arial",10,"bold"),bg="#7E84F7")
        l6.place(relx=0.05,rely=0.4)
        l7=Label(frame,text="PAN No",font=("arial",10,"bold"),bg="#7E84F7")
        l7.place(relx=0.05,rely=0.45)
        l8=Label(frame,text="HSC Reg no",font=("arial",10,"bold"),bg="#7E84F7")
        l8.place(relx=0.05,rely=0.5)
        l9=Label(frame,text="Degree Reg No",font=("arial",10,"bold"),bg="#7E84F7")
        l9.place(relx=0.05,rely=0.55)
        l10=Label(frame,text="HSC Percentage",font=("arial",10,"bold"),bg="#7E84F7")
        l10.place(relx=0.05,rely=0.6)
        l11=Label(frame,text="Degree Percentage",font=("arial",10,"bold"),bg="#7E84F7")
        l11.place(relx=0.05,rely=0.65)
        l12=Label(frame,text="DOJ",font=("arial",10,"bold"),bg="#7E84F7")
        l12.place(relx=0.05,rely=0.7)
        l13=Label(frame,text="Experience",font=("arial",10,"bold"),bg="#7E84F7")
        l13.place(relx=0.05,rely=0.75)
        l14=Label(frame,text="Project",font=("arial",10,"bold"),bg="#7E84F7")
        l14.place(relx=0.05,rely=0.8)
        '''
        e0.delete(0,END)
        e1.delete(0,END)
        e2.delete(0,END)
        e3.delete(0,END)
        e4.delete(0,END)
        e5.delete(0,END)
        e6.delete(0,END)
        e7.delete(0,END)
        e8.delete(0,END)
        e9.delete(0,END)
        e10.delete(0,END)
        e11.delete(0,END)
        e12.delete(0,END)
        e13.delete(0,END)
        '''
        e0=Entry(b)
        e0.place(relx=0.2,rely=0.15)
        e1=Entry(b)
        e1.place(relx=0.2,rely=0.2)
        e2=Entry(b)
        e2.place(relx=0.2,rely=0.25)
        e3=Entry(b)
        e3.place(relx=0.2,rely=0.3)
        e4=Entry(b)
        e4.place(relx=0.2,rely=0.35)
        e5=Entry(b)
        e5.place(relx=0.2,rely=0.4)
        e6=Entry(b)
        e6.place(relx=0.2,rely=0.45)
        e7=Entry(b)
        e7.place(relx=0.2,rely=0.5)
        e8=Entry(b)
        e8.place(relx=0.2,rely=0.55)
        e9=Entry(b)
        e9.place(relx=0.2,rely=0.6)
        e10=Entry(b)
        e10.place(relx=0.2,rely=0.65)
        e11=Entry(b)
        e11.place(relx=0.2,rely=0.7)
        e12=Entry(b)
        e12.place(relx=0.2,rely=0.75)
        e13=Entry(b)
        e13.place(relx=0.2,rely=0.8)
     
        
        def submit():
            file=open("Current Employee.txt","a")
            file.write("\n"+e0.get()+"\t"+e1.get()+"\t"+e2.get()+"\t"+e3.get()+"\t"+e4.get()+"\t"+e5.get()+"\t"+e6.get()+"\t"+e7.get()+"\t"+e8.get()+"\t"+e9.get()+"\t"+e10.get()+"\t"+e11.get()+"\t"+e12.get()+"\t"+e13.get()+"\n")
            file=open("Current Employee.txt","r")
            data=file.read().split("\n")
            print(data)
            for x in data:
                info=x.split("\t")
            a=int(e0.get())
            b=str(e13.get())
            '''
            #a=int(input("Enter employee ID:"))
            if(a==1):
               print("The current project is",b)
            elif(a==2):
                print("The current project is",b)
            elif(a==3):
                print("The current project is",b)
            elif(a==4):
                print("The current project is",b)
            elif(a==5):
                print("The current project is",b)
            else:
                print("You entered a wrong ID")'''
       
        Button(frame,text="Submit",bg="#7E84F7",font=("arial",15,"bold"),command=lambda:submit()).place(relx=0.25,rely=0.8)
        b.mainloop()
    
        
    b3=Button(frame,text="Employee Details",bg="#7E84F7",font=("Times New Roman",15,"bold"))
    b3.place(relx=0.3,rely=0.4)
    b2=Button(frame,text="Current Employee",font=("Times New Roman",15,"bold"),bg="#7E84F7",command=lambda:exist(b))
    b2.place(relx=0.4,rely=0.4)
    b.mainloop()

b1=Button(frame,text="Admin Login",bg="#7E84F7",font=("Times New Roman",20,"bold"),command=lambda:admin(b))
b1.place(relx=0.2,rely=0.5)


def emp(b):
    
    b.destroy()
    b=Tk()
    b.title("Employee Record")
    b.geometry("1600x800")
    b.configure(bg="#7E84F7")
    frame=Frame(b,width=1600,height=600,background="#7E84F7")
    frame.pack()
    frame.place(relx=0,rely=0)
    # img=ImageTk.PhotoImage(Image.open("D:\\python\\gui\\employ.gif"))
    # l0=Label(frame,image=img)
    # l0.pack()
    
    l1=Label(frame,text="Employee Record",font=("calibiri",30,"italic","bold"),bg="#7E84F7",fg="white")
    l1.place(relx=0.2,rely=0.1)
    l2=Label(frame,text="Details of current project",font=("arial",15,"bold","italic"),bg="#7E84F7")
    l2.place(relx=0.05,rely=0.4)
    l3=Label(frame,text="Name",font=("arial",15,"italic","bold"),bg="#7E84F7")
    l3.place(relx=0.05,rely=0.2)
    l4=Label(frame,text="Employee ID",font=("arial",15,"italic","bold"),bg="#7E84F7")
    l4.place(relx=0.05,rely=0.3)
    mystr=StringVar()
    mystr.set('0')
    e1=Entry(b)
    e1.place(relx=0.25,rely=0.2)
    e2=Entry(b)
    e2.place(relx=0.25,rely=0.3)
    e3=Entry(b,textvar=mystr,state=DISABLED)
    e3.place(relx=0.25,rely=0.4)
    def show():
        file=open("Current Employee.txt","r")
        data=file.read().split("\n")
        print(data)
        for x in data:
            info=x.split("\t")
            print(info)
            if info[0]==e2.get() and info[1]==e1.get():
                mystr.set(info[13])
        else:
            print("sorry")
        
            
    c=Button(frame,text="Click",font=("Calibiri",15,"bold"),command=lambda:show())
    c.place(relx=0.3,rely=0.5)
    b.mainloop()
    
b2=Button(frame,text="Employee Login",bg="#7E84F7",font=("Times New Roman",20,"bold"),command=lambda:emp(b))
b2.place(relx=0.4,rely=0.5)
b.mainloop()
